name: Artifacts
on: [pull_request, workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            arch: aarch64
          - os: windows-latest
            arch: x86
          - os: windows-latest
            arch: x86_64
          # macOS builds
          - os: macos-latest
            arch: aarch64
          - os: macos-latest
            arch: x86_64
          # Linux builds
          - os: ubuntu-latest
            arch: aarch64
          - os: ubuntu-latest
            arch: armv7a
          - os: ubuntu-latest
            arch: powerpc64le
          - os: ubuntu-latest
            arch: riscv64
          - os: ubuntu-latest
            arch: s390x
          - os: ubuntu-latest
            arch: x86
          - os: ubuntu-latest
            arch: x86_64
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - run: |
          zig build ci --summary all
      - name: get version
        id: version
        run: |
          zig build version > $GITHUB_OUTPUT
      - if: ${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'x86_64' }}
        uses: actions/upload-artifact@v4
        with:
          name: ninja-archives-${{ steps.version.outputs.version }}
          path: |
            zig-out/ninja-x86_64-windows.zip
            zig-out/ninja-aarch64-windows.zip
            zig-out/ninja-x86-windows.zip
            zig-out/ninja-x86_64-macos.tar.gz
            zig-out/ninja-aarch64-macos.tar.gz
            zig-out/ninja-x86_64-linux.tar.gz
            zig-out/ninja-aarch64-linux.tar.gz
            zig-out/ninja-arm-linux.tar.gz
            zig-out/ninja-powerpc64le-linux.tar.gz
            zig-out/ninja-riscv64-linux.tar.gz
            zig-out/ninja-s390x-linux.tar.gz
            zig-out/ninja-x86-linux.tar.gz
